spring.application.name=medisphere-backend

spring.mongodb.uri=mongodb+srv://abiramishankar57_db_user:jQt78nNdWAyzrSyz@medisphere-cluster.abzjyqm.mongodb.net/?appName=medisphere-cluster
spring.mongodb.database=medispheremono